name: Update Submodules and Build Docker Images

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual triggering

jobs:  
  update-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}  # Personal access token with repo permissions

      # Update submodules section
      - name: Update submodules
        run: |
          git submodule update --remote --recursive

      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if submodules changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Updated the submodules for creating images"
          git push

      # Docker build section
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: DtruAlex
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Server image
        uses: docker/build-push-action@v4
        with:
          context: ./Server
          push: true
          tags: |
            ghcr.io/aristocratiilite-itfest2025/aristocratii-server:latest
            ghcr.io/aristocratiilite-itfest2025/aristocratii-serverr:${{ github.sha }}

      - name: Build and push Client image
        uses: docker/build-push-action@v4
        with:
          context: ./Client
          push: true
          tags: |
            ghcr.io/aristocratiilite-itfest2025/aristocratii-client:latest
            ghcr.io/aristocratiilite-itfest2025/aristocratii-client:${{ github.sha }}
